'use client';

import React from 'react';
import Interventions from '@/app/components/Interventions';

// Sample data structure matching the specified headers
const sampleData = [
  {
    firstName: "John",
    lastName: "Adams",
    id: 1234567,
    quarter: "Q3",
    progressReportFs: 2,
    finalGradeFs: 1,
    elaStarBand: "Basic",
    mathStarBand: "Below Basic",
    referrals: 3,
    suspensionDays: 1,
    academicInterventionLevel: 2,
    behavioralInterventionLevel: 1,
    attendanceInterventionLevel: 1,
    isSped: false,
    isEL: false,
    costReferralSubmitted: true,
    sc: 40
  },
  {
    firstName: "Sarah",
    lastName: "Brown",
    id: 1234568,
    quarter: "Q3",
    progressReportFs: 4,
    finalGradeFs: 3,
    elaStarBand: "Below Basic",
    mathStarBand: "Far Below Basic",
    referrals: 5,
    suspensionDays: 3,
    academicInterventionLevel: 3,
    behavioralInterventionLevel: 2,
    attendanceInterventionLevel: 3,
    isSped: false,
    isEL: true,
    costReferralSubmitted: true,
    sc: 40
  },
  {
    firstName: "David",
    lastName: "Chen",
    id: 1234569,
    quarter: "Q3",
    progressReportFs: 0,
    finalGradeFs: 0,
    elaStarBand: "Proficient",
    mathStarBand: "Advanced",
    referrals: 0,
    suspensionDays: 0,
    academicInterventionLevel: 0,
    behavioralInterventionLevel: 0,
    attendanceInterventionLevel: 0,
    isSped: false,
    isEL: false,
    costReferralSubmitted: false,
    sc: 40
  },
  {
    firstName: "Alicia",
    lastName: "Davis",
    id: 1234570,
    quarter: "Q3",
    progressReportFs: 1,
    finalGradeFs: 0,
    elaStarBand: "Basic",
    mathStarBand: "Basic",
    referrals: 0,
    suspensionDays: 0,
    academicInterventionLevel: 1,
    behavioralInterventionLevel: 0,
    attendanceInterventionLevel: 2,
    isSped: true,
    isEL: false,
    costReferralSubmitted: true,
    sc: 40
  },
  {
    firstName: "Michael",
    lastName: "Evans",
    id: 1234571,
    quarter: "Q3",
    progressReportFs: 3,
    finalGradeFs: 2,
    elaStarBand: "Below Basic",
    mathStarBand: "Basic",
    referrals: 2,
    suspensionDays: 0,
    academicInterventionLevel: 2,
    behavioralInterventionLevel: 1,
    attendanceInterventionLevel: 2,
    isSped: false,
    isEL: false,
    costReferralSubmitted: true,
    sc: 40
  },
  {
    firstName: "Zoe",
    lastName: "Franklin",
    id: 1234572,
    quarter: "Q3",
    progressReportFs: 5,
    finalGradeFs: 4,
    elaStarBand: "Far Below Basic",
    mathStarBand: "Below Basic",
    referrals: 7,
    suspensionDays: 5,
    academicInterventionLevel: 3,
    behavioralInterventionLevel: 3,
    attendanceInterventionLevel: 3,
    isSped: true,
    isEL: false,
    costReferralSubmitted: true,
    sc: 40
  },
  {
    firstName: "Luis",
    lastName: "Garcia",
    id: 1234573,
    quarter: "Q3",
    progressReportFs: 1,
    finalGradeFs: 0,
    elaStarBand: "Basic",
    mathStarBand: "Basic",
    referrals: 1,
    suspensionDays: 0,
    academicInterventionLevel: 1,
    behavioralInterventionLevel: 1,
    attendanceInterventionLevel: 1,
    isSped: false,
    isEL: true,
    costReferralSubmitted: false,
    sc: 40
  },
  {
    firstName: "Maria",
    lastName: "Hernandez",
    id: 1234574,
    quarter: "Q3",
    progressReportFs: 2,
    finalGradeFs: 1,
    elaStarBand: "Basic",
    mathStarBand: "Below Basic",
    referrals: 0,
    suspensionDays: 0,
    academicInterventionLevel: 1,
    behavioralInterventionLevel: 0,
    attendanceInterventionLevel: 1,
    isSped: false,
    isEL: true,
    costReferralSubmitted: true,
    sc: 40
  },
  {
    firstName: "Darius",
    lastName: "Jackson",
    id: 1234575,
    quarter: "Q3",
    progressReportFs: 5,
    finalGradeFs: 4,
    elaStarBand: "Below Basic",
    mathStarBand: "Far Below Basic",
    referrals: 6,
    suspensionDays: 3,
    academicInterventionLevel: 3,
    behavioralInterventionLevel: 3,
    attendanceInterventionLevel: 2,
    isSped: true,
    isEL: false,
    costReferralSubmitted: true,
    sc: 40
  },
  {
    firstName: "Ji-Young",
    lastName: "Kim",
    id: 1234576,
    quarter: "Q3",
    progressReportFs: 0,
    finalGradeFs: 0,
    elaStarBand: "Advanced",
    mathStarBand: "Advanced",
    referrals: 0,
    suspensionDays: 0,
    academicInterventionLevel: 0,
    behavioralInterventionLevel: 0,
    attendanceInterventionLevel: 0,
    isSped: false,
    isEL: true,
    costReferralSubmitted: false,
    sc: 40
  }
];

const InterventionsPage = () => {
  return (
    <div className="w-full px-2 py-4">
      <h1 className="text-3xl font-bold mb-4">Student Interventions Dashboard</h1>
      <Interventions data={sampleData} title="Student Interventions" />
    </div>
  );
};

export default InterventionsPage;