/**
 * Custom Query Execution Endpoint
 *
 * Executes SQL queries generated by the form-based query builder.
 * Injects school security filters automatically based on user permissions.
 */

import { NextResponse } from 'next/server';
import { auth, SessionUser } from '@/auth';
import { runQuery } from '@/lib/aeries';
import { checkRateLimit, getRateLimitIdentifier } from '@/lib/rateLimit';
import { validateSql as validateSqlStrict } from '@/lib/ai-query/sql-validator';
import { viewQueryBuilder } from '@/lib/ai-query/view-query-builder';
import { SCHOOL_NAMES } from '@/lib/constants/schools';

export async function POST(request: Request) {
  const startTime = Date.now();

  try {
    // Check authentication
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const user = session.user as unknown as SessionUser;

    // Rate limiting: 20 requests per 30 seconds per user
    const identifier = await getRateLimitIdentifier(request, user.id);
    const rateLimit = checkRateLimit(identifier, {
      maxRequests: 20,
      windowSeconds: 30,
    });

    if (!rateLimit.success) {
      return NextResponse.json(
        {
          error: 'Too many requests',
          message: `Rate limit exceeded. Try again after ${new Date(rateLimit.reset).toLocaleTimeString()}`,
        },
        {
          status: 429,
          headers: {
            'X-RateLimit-Limit': rateLimit.limit.toString(),
            'X-RateLimit-Remaining': rateLimit.remaining.toString(),
            'X-RateLimit-Reset': rateLimit.reset.toString(),
            'Retry-After': Math.ceil((rateLimit.reset - Date.now()) / 1000).toString(),
          },
        }
      );
    }

    const activeSchool = user.activeSchool ?? -1;
    const allowedSchools = user.schools || [];

    // Deny access if no school set
    if (activeSchool === -1) {
      return NextResponse.json({
        error: 'No school access. Please select a school from the school picker.'
      }, { status: 403 });
    }

    // Get request body
    const body = await request.json();
    const { sql, schoolFilter } = body;

    if (!sql?.trim()) {
      return NextResponse.json({ error: 'SQL query is required' }, { status: 400 });
    }

    // Validate SQL with the strict validator: SELECT-only, llm_* view whitelist,
    // blocked base tables, and no multi-statement injection.
    const validation = validateSqlStrict(sql);
    if (!validation.valid) {
      return NextResponse.json({
        success: false,
        error: validation.errors.join('; ')
      }, { status: 400 });
    }

    // Determine school filter
    let schoolsToFilter: string[];

    if (activeSchool === 0) {
      // District-wide mode
      if (schoolFilter && schoolFilter.length > 0) {
        // User selected specific schools, but verify they have access
        schoolsToFilter = schoolFilter.filter((s: string) =>
          allowedSchools.length === 0 || allowedSchools.includes(s)
        );
      } else {
        // No specific selection, use all allowed schools
        schoolsToFilter = allowedSchools.length > 0 ? allowedSchools : [];
      }
    } else {
      // Single school mode
      schoolsToFilter = [activeSchool.toString()];
    }

    // Deny by default: a non-admin whose query resolves to no school filter would
    // otherwise read across all schools. Only full admins may run unscoped.
    if (schoolsToFilter.length === 0 && !user.admin) {
      return NextResponse.json({
        success: false,
        error: 'No accessible schools resolved for this query.'
      }, { status: 403 });
    }

    // Inject school security filter (detects the real view alias and
    // parenthesizes any existing predicate so OR can't escape the scope)
    const securedSql = viewQueryBuilder.injectSecurityFilters(sql, schoolsToFilter);

    if (process.env.AI_QUERY_DEBUG === 'true') {
      console.log('[Custom Query] Executing:', securedSql);
    }

    // Execute query
    const queryResult = await runQuery(securedSql);
    const data = queryResult as any[] | null;
    const rowCount = data?.length || 0;

    const duration = Date.now() - startTime;

    console.log(`[Custom Query] Returned ${rowCount} rows in ${duration}ms`);

    return NextResponse.json({
      success: true,
      data: data,
      rowCount: rowCount,
      executedSql: securedSql,
      metadata: {
        durationMs: duration,
        schoolScope: activeSchool === 0
          ? (schoolsToFilter.length > 0
            ? `${schoolsToFilter.length} schools`
            : 'All schools')
          : SCHOOL_NAMES[activeSchool.toString()] || `School ${activeSchool}`,
      }
    });

  } catch (error) {
    const duration = Date.now() - startTime;
    console.error('[Custom Query] Error:', error);

    return NextResponse.json({
      success: false,
      error: error instanceof Error ? error.message : 'Query execution failed',
      durationMs: duration
    }, { status: 500 });
  }
}
