/**
 * View-Based AI Query Generation Engine
 *
 * Core pipeline: LLM -> clean -> validate -> inject security filters -> execute,
 * wrapped in a repair loop that feeds BOTH validation errors and MSSQL execution
 * errors back to the LLM for correction.
 *
 * Extracted from the view-generate API route so it can run without HTTP/auth
 * (e.g. the eval harness in scripts/eval-ai-query.ts).
 */

import { createLLMClient, LLMClient, ChatMessage } from '@/lib/llm-client';
import { buildViewSystemPrompt, buildCompactViewPrompt } from './view-prompt-builder';
import { selectRelevantViews } from './view-selector';
import { VIEW_SCHEMAS } from './view-schema.generated';
import { ViewQueryBuilder } from './view-query-builder';
import { ValidationResult } from './sql-validator';

// Total attempt budget shared by validation and execution failures
export const MAX_TOTAL_ATTEMPTS = 4;

const DEBUG = process.env.AI_QUERY_DEBUG === 'true';

// Connection-level errors the LLM can't fix - fail fast instead of burning attempts
const NON_REPAIRABLE_ERROR =
  /ETIMEOUT|ECONNCLOSED|ECONNRESET|ELOGIN|ESOCKET|EALREADYCONNECTING|Failed to connect|Login failed|Database Connection Failed|Connection is closed|Connection lost|Request failed to complete/i;

// Tracks each query generation attempt for debugging
export interface QueryAttempt {
  attemptNumber: number;
  sql: string;
  rawResponse: string;
  validation: ValidationResult;
  /** SQL actually sent to the database (after security filter injection) */
  executedSql?: string;
  /** MSSQL error message if execution failed */
  executionError?: string;
  correctionPrompt?: string;
}

/** Live progress notification emitted during generation (for streaming UIs) */
export interface GenerationProgressEvent {
  stage:
    | 'selecting'
    | 'generating'
    | 'validating'
    | 'validation_failed'
    | 'executing'
    | 'execution_failed';
  /** 0 while selecting views, then the current attempt number */
  attempt: number;
  /** Short human-readable status line */
  message: string;
  /** Extra context: view names, error snippets */
  detail?: string;
}

export interface GenerateViewQueryOptions {
  /** The user's natural-language request (used in correction prompts) */
  prompt: string;
  /** Full first user message if different from prompt (e.g. with school-scope note) */
  contextPrompt?: string;
  /** School codes to inject as security filter; [] = no filter (district-wide) */
  schools: string[];
  /** Execute the generated SQL (default true) */
  execute?: boolean;
  /** SQL executor override (defaults to runQuery) - used by the eval harness */
  runner?: (sql: string) => Promise<unknown>;
  /** LLM client override */
  llm?: LLMClient;
  /** Called at each pipeline stage - drives streaming progress UIs */
  onProgress?: (event: GenerationProgressEvent) => void;
}

export interface GenerateViewQueryResult {
  success: boolean;
  /** Final SQL with security filters injected (last attempt's SQL on failure) */
  sql: string;
  /** SQL as generated by the LLM, before security filter injection */
  originalSql: string;
  data: unknown[] | null;
  rowCount: number;
  executed: boolean;
  validation: ValidationResult;
  attempts: QueryAttempt[];
  /** Views the prompt was pruned to (all views = no pruning applied) */
  selectedViews: string[];
  /** Last raw LLM response */
  raw: string;
  /** Top-level failure description when success is false */
  error?: string;
  /** Last execution error message, if any */
  executeError?: string;
  llmUsage?: { promptTokens: number; completionTokens: number };
  durationMs: number;
}

/**
 * Build a correction prompt to help the LLM fix validation errors
 */
function buildCorrectionPrompt(originalPrompt: string, failedSql: string, errors: string[]): string {
  return `Your previous SQL query had validation errors. Please fix them and try again.

ORIGINAL REQUEST: ${originalPrompt}

YOUR PREVIOUS SQL (with errors):
${failedSql}

VALIDATION ERRORS:
${errors.map((e, i) => `${i + 1}. ${e}`).join('\n')}

IMPORTANT REMINDERS:
- Only use the EXACT view names listed in the schema (llm_student_demographics, llm_attendance_summary, etc.)
- Do NOT invent view names - if unsure, use llm_student_demographics as the base
- Use EXACT column names from the schema - do not abbreviate or modify them
- Return ONLY the corrected SQL query, no explanations

Please provide the corrected SQL query:`;
}

/**
 * Targeted fix instruction for common MSSQL error classes - a specific hint
 * repairs far more reliably than the raw error alone (especially for small models)
 */
function executionHint(dbError: string): string {
  if (/Ambiguous column name/i.test(dbError)) {
    return '\nFIX: alias-qualify EVERY column reference (e.g. d.first_name instead of first_name) in SELECT, WHERE, GROUP BY, and ORDER BY.';
  }
  if (/Invalid object name/i.test(dbError)) {
    return `\nFIX: you referenced a view that does not exist. Use ONLY these views: ${Object.keys(VIEW_SCHEMAS).join(', ')}.`;
  }
  if (/Invalid column name/i.test(dbError)) {
    return '\nFIX: you referenced a column that does not exist. Use ONLY exact column names from the schema.';
  }
  if (/Conversion failed/i.test(dbError)) {
    return "\nFIX: a value has the wrong type for its column - text flags need quoted values like 'Yes', numeric flags need 1 or 0.";
  }
  return '';
}

/**
 * Build a correction prompt from a real MSSQL execution error
 */
function buildExecutionCorrectionPrompt(originalPrompt: string, failedSql: string, dbError: string): string {
  return `Your previous SQL query passed validation but FAILED when executed against SQL Server. Please fix it and try again.

ORIGINAL REQUEST: ${originalPrompt}

YOUR PREVIOUS SQL (failed at execution):
${failedSql}

SQL SERVER ERROR:
${dbError}${executionHint(dbError)}

IMPORTANT REMINDERS:
- This is Microsoft SQL Server (T-SQL) - use T-SQL syntax and functions only
- Check data types: BIT columns compare to 1/0, dates need valid CONVERT/CAST logic, avoid implicit string-to-number conversions
- Use EXACT view and column names from the schema
- Return ONLY the corrected SQL query, no explanations

Please provide the corrected SQL query:`;
}

/**
 * Generate (and optionally execute) a SQL query from a natural-language prompt,
 * repairing validation AND execution failures via LLM feedback.
 */
export async function generateViewQuery(
  options: GenerateViewQueryOptions
): Promise<GenerateViewQueryResult> {
  const startTime = Date.now();
  const execute = options.execute !== false;
  // A throwing progress callback must never kill generation
  const emit = (event: GenerationProgressEvent) => {
    try {
      options.onProgress?.(event);
    } catch {
      /* ignore */
    }
  };
  // Lazy-load the default runner so this module stays importable outside
  // Next.js (lib/aeries.ts pulls in the auth stack)
  const runner =
    options.runner ??
    (async (sql: string) => {
      const { runQuery } = await import('@/lib/aeries');
      return runQuery(sql);
    });
  const llm = options.llm ?? createLLMClient();

  const useCompactPrompt = process.env.LLM_COMPACT_PROMPT === 'true';

  // Prune the schema to the views relevant to this request - better column
  // recall for small models and less prompt to process. Attempts 3+ fall back
  // to the full prompt in case the pruning excluded a view the query needs.
  const selectedViews = selectRelevantViews(`${options.prompt}\n${options.contextPrompt ?? ''}`);
  const prunedPrompt = useCompactPrompt ? buildCompactViewPrompt() : buildViewSystemPrompt(selectedViews);
  const fullPrompt = useCompactPrompt ? buildCompactViewPrompt() : buildViewSystemPrompt();

  emit({
    stage: 'selecting',
    attempt: 0,
    message: `Selected ${selectedViews.length} relevant view${selectedViews.length === 1 ? '' : 's'}`,
    detail: selectedViews.join(', '),
  });

  const builder = new ViewQueryBuilder();
  const attempts: QueryAttempt[] = [];

  let sql = '';
  let securedSql = '';
  let raw = '';
  let validation: ValidationResult = { valid: false, errors: [], warnings: [], referencedViews: [] };
  let data: unknown[] | null = null;
  let rowCount = 0;
  let executed = false;
  let executeError: string | undefined;
  let llmUsage: { promptTokens: number; completionTokens: number } | undefined;

  for (let attemptNumber = 1; attemptNumber <= MAX_TOTAL_ATTEMPTS; attemptNumber++) {
    // Build the messages for this attempt
    const messages: ChatMessage[] = [
      { role: 'system', content: attemptNumber >= 3 ? fullPrompt : prunedPrompt },
      { role: 'user', content: options.contextPrompt ?? options.prompt },
    ];

    let correctionPrompt: string | undefined;
    const previousAttempt = attempts[attempts.length - 1];
    if (previousAttempt) {
      // Feed back the PRE-injection SQL - the injected security filter is not
      // the LLM's to fix
      correctionPrompt = previousAttempt.executionError
        ? buildExecutionCorrectionPrompt(options.prompt, previousAttempt.sql, previousAttempt.executionError)
        : buildCorrectionPrompt(options.prompt, previousAttempt.sql, previousAttempt.validation.errors);
      messages.push({ role: 'assistant', content: previousAttempt.sql });
      messages.push({ role: 'user', content: correctionPrompt });
    }

    if (DEBUG) console.log(`[View AI Query] Attempt ${attemptNumber}/${MAX_TOTAL_ATTEMPTS}...`);
    emit({
      stage: 'generating',
      attempt: attemptNumber,
      message: attemptNumber === 1
        ? 'Writing SQL'
        : `Rewriting SQL with the fix (attempt ${attemptNumber} of ${MAX_TOTAL_ATTEMPTS})`,
    });

    const llmResponse = await llm.chat(messages);
    llmUsage = llmResponse.usage ?? llmUsage;
    raw = llmResponse.content;

    sql = builder.cleanLlmResponse(llmResponse.content);
    if (DEBUG) console.log(`[View AI Query] Attempt ${attemptNumber} - Cleaned SQL:`, sql);

    emit({ stage: 'validating', attempt: attemptNumber, message: 'Checking against database schema' });
    validation = builder.validate(sql);

    const attempt: QueryAttempt = {
      attemptNumber,
      sql,
      rawResponse: llmResponse.content,
      validation,
      correctionPrompt,
    };
    attempts.push(attempt);

    if (!validation.valid) {
      if (DEBUG) console.warn(`[View AI Query] Attempt ${attemptNumber} - Validation failed:`, validation.errors);
      emit({
        stage: 'validation_failed',
        attempt: attemptNumber,
        message: 'SQL failed schema checks',
        detail: validation.errors[0],
      });
      continue;
    }

    // Inject school security filter (always, even when not executing, so the
    // returned SQL is safe to run as-is)
    securedSql = builder.injectSecurityFilters(sql, options.schools);
    attempt.executedSql = securedSql;

    if (!execute) break;

    try {
      if (DEBUG) console.log(`[View AI Query] Attempt ${attemptNumber} - Executing...`);
      emit({ stage: 'executing', attempt: attemptNumber, message: 'Running against Aeries' });
      const result = await runner(securedSql);
      data = Array.isArray(result) ? result : [];
      rowCount = data.length;
      executed = true;
      executeError = undefined;
      break;
    } catch (execError) {
      const message = execError instanceof Error ? execError.message : String(execError);
      attempt.executionError = message;
      executeError = message;
      if (DEBUG) console.warn(`[View AI Query] Attempt ${attemptNumber} - Execution failed:`, message);
      emit({
        stage: 'execution_failed',
        attempt: attemptNumber,
        message: 'Database reported an error',
        detail: message,
      });

      if (NON_REPAIRABLE_ERROR.test(message)) {
        // Connection-level problem - retrying with a different query won't help
        break;
      }
    }
  }

  const success = validation.valid && (!execute || executed);

  let error: string | undefined;
  if (!validation.valid) {
    error = 'Invalid SQL generated after multiple attempts';
  } else if (execute && !executed) {
    error = 'Query execution failed after multiple attempts';
  }

  return {
    success,
    sql: securedSql || sql,
    originalSql: sql,
    data,
    rowCount,
    executed,
    validation,
    attempts,
    selectedViews,
    raw,
    error,
    executeError,
    llmUsage,
    durationMs: Date.now() - startTime,
  };
}
