/**
 * AUTO-GENERATED by scripts/generate-view-schema.ts - DO NOT EDIT BY HAND.
 *
 * Source: INFORMATION_SCHEMA of DST25000SanLeandroUSD
 * Views: 25, columns: 530
 *
 * Regenerate with: npm run generate:view-schema
 */

export interface ViewColumn {
  name: string;
  dataType: string;
  /** Sampled distinct values for text-typed flag columns (e.g. 'Yes'/'No') */
  exampleValues?: string[];
}

export const VIEW_SCHEMAS: Record<string, ViewColumn[]> = {
  "llm_all_sections": [
    {
      "name": "section_id",
      "dataType": "varchar"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "term",
      "dataType": "varchar"
    },
    {
      "name": "period",
      "dataType": "varchar"
    },
    {
      "name": "course_id",
      "dataType": "varchar"
    },
    {
      "name": "course_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_staff_id",
      "dataType": "int"
    },
    {
      "name": "teacher_number",
      "dataType": "int"
    },
    {
      "name": "teacher_last_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_first_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_email",
      "dataType": "varchar"
    },
    {
      "name": "room_number",
      "dataType": "varchar"
    },
    {
      "name": "grade_high",
      "dataType": "int"
    },
    {
      "name": "grade_low",
      "dataType": "int"
    },
    {
      "name": "school_level",
      "dataType": "varchar"
    },
    {
      "name": "student_count",
      "dataType": "int"
    }
  ],
  "llm_attendance_daily": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "day_number",
      "dataType": "int"
    },
    {
      "name": "attendance_date",
      "dataType": "date"
    },
    {
      "name": "day_of_week",
      "dataType": "varchar"
    },
    {
      "name": "all_day_code",
      "dataType": "varchar"
    },
    {
      "name": "all_day_description",
      "dataType": "varchar"
    },
    {
      "name": "all_day_status",
      "dataType": "varchar"
    },
    {
      "name": "all_day_counts_as_present",
      "dataType": "bit"
    },
    {
      "name": "all_day_suspension_related",
      "dataType": "bit"
    },
    {
      "name": "period_0_code",
      "dataType": "varchar"
    },
    {
      "name": "period_1_code",
      "dataType": "varchar"
    },
    {
      "name": "period_2_code",
      "dataType": "varchar"
    },
    {
      "name": "period_3_code",
      "dataType": "varchar"
    },
    {
      "name": "period_4_code",
      "dataType": "varchar"
    },
    {
      "name": "period_5_code",
      "dataType": "varchar"
    },
    {
      "name": "period_6_code",
      "dataType": "varchar"
    },
    {
      "name": "period_absence_count",
      "dataType": "int"
    },
    {
      "name": "overall_attendance_code",
      "dataType": "varchar"
    },
    {
      "name": "was_absent_all_day",
      "dataType": "int"
    },
    {
      "name": "is_suspension_absence",
      "dataType": "int"
    }
  ],
  "llm_attendance_summary": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "instructional_days",
      "dataType": "int"
    },
    {
      "name": "days_present",
      "dataType": "int"
    },
    {
      "name": "days_absent",
      "dataType": "int"
    },
    {
      "name": "suspension_days",
      "dataType": "int"
    },
    {
      "name": "unexcused_absences",
      "dataType": "int"
    },
    {
      "name": "tardies",
      "dataType": "int"
    },
    {
      "name": "attendance_rate_percent",
      "dataType": "float"
    },
    {
      "name": "absence_rate_percent",
      "dataType": "float"
    },
    {
      "name": "is_chronically_absent",
      "dataType": "varchar",
      "exampleValues": [
        "Yes",
        "No"
      ]
    },
    {
      "name": "truancy_risk_level",
      "dataType": "varchar"
    }
  ],
  "llm_class_rosters": [
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "section_number",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "course_number",
      "dataType": "varchar"
    },
    {
      "name": "course_name",
      "dataType": "varchar"
    },
    {
      "name": "course_description",
      "dataType": "varchar"
    },
    {
      "name": "department_name",
      "dataType": "varchar"
    },
    {
      "name": "period",
      "dataType": "int"
    },
    {
      "name": "room_number",
      "dataType": "varchar"
    },
    {
      "name": "teacher_number",
      "dataType": "int"
    },
    {
      "name": "teacher_last_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_first_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_email",
      "dataType": "varchar"
    },
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "student_last_name",
      "dataType": "varchar"
    },
    {
      "name": "student_first_name",
      "dataType": "varchar"
    },
    {
      "name": "student_grade_level",
      "dataType": "int"
    },
    {
      "name": "student_email",
      "dataType": "varchar"
    },
    {
      "name": "enrollment_status",
      "dataType": "varchar"
    },
    {
      "name": "current_class_size",
      "dataType": "int"
    }
  ],
  "llm_course_enrollments": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "section_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "course_number",
      "dataType": "varchar"
    },
    {
      "name": "course_name",
      "dataType": "varchar"
    },
    {
      "name": "course_description",
      "dataType": "varchar"
    },
    {
      "name": "department_code",
      "dataType": "varchar"
    },
    {
      "name": "department_name",
      "dataType": "varchar"
    },
    {
      "name": "state_course_code",
      "dataType": "varchar"
    },
    {
      "name": "section_id",
      "dataType": "int"
    },
    {
      "name": "period",
      "dataType": "int"
    },
    {
      "name": "room_number",
      "dataType": "varchar"
    },
    {
      "name": "teacher_number",
      "dataType": "int"
    },
    {
      "name": "teacher_last_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_first_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_email",
      "dataType": "varchar"
    },
    {
      "name": "schedule_mode",
      "dataType": "varchar"
    },
    {
      "name": "schedule_mode_description",
      "dataType": "varchar"
    },
    {
      "name": "enrollment_status",
      "dataType": "varchar"
    },
    {
      "name": "credits",
      "dataType": "decimal"
    },
    {
      "name": "track",
      "dataType": "varchar"
    },
    {
      "name": "is_currently_enrolled",
      "dataType": "int"
    }
  ],
  "llm_discipline_incidents": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "sequence_number",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "incident_school_code",
      "dataType": "int"
    },
    {
      "name": "incident_school_name",
      "dataType": "varchar"
    },
    {
      "name": "incident_date",
      "dataType": "date"
    },
    {
      "name": "primary_discipline_code",
      "dataType": "varchar"
    },
    {
      "name": "primary_discipline_description",
      "dataType": "varchar"
    },
    {
      "name": "secondary_code_1",
      "dataType": "varchar"
    },
    {
      "name": "secondary_description_1",
      "dataType": "varchar"
    },
    {
      "name": "secondary_code_2",
      "dataType": "varchar"
    },
    {
      "name": "secondary_description_2",
      "dataType": "varchar"
    },
    {
      "name": "secondary_code_3",
      "dataType": "varchar"
    },
    {
      "name": "secondary_description_3",
      "dataType": "varchar"
    },
    {
      "name": "secondary_code_4",
      "dataType": "varchar"
    },
    {
      "name": "secondary_description_4",
      "dataType": "varchar"
    },
    {
      "name": "incident_comment",
      "dataType": "varchar"
    },
    {
      "name": "disposition_code",
      "dataType": "varchar"
    },
    {
      "name": "disposition_description",
      "dataType": "varchar"
    },
    {
      "name": "discipline_category",
      "dataType": "varchar"
    },
    {
      "name": "is_out_of_school_suspension",
      "dataType": "int"
    },
    {
      "name": "is_in_school_suspension",
      "dataType": "int"
    },
    {
      "name": "is_expulsion",
      "dataType": "int"
    },
    {
      "name": "is_suspension",
      "dataType": "int"
    },
    {
      "name": "school_year_start",
      "dataType": "int"
    }
  ],
  "llm_elementary_grades": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "homeroom_teacher_number",
      "dataType": "int"
    },
    {
      "name": "teacher_last_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_first_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_email",
      "dataType": "varchar"
    },
    {
      "name": "room_number",
      "dataType": "varchar"
    },
    {
      "name": "teacher_grade_low",
      "dataType": "int"
    },
    {
      "name": "teacher_grade_high",
      "dataType": "int"
    },
    {
      "name": "teacher_grade_range",
      "dataType": "varchar"
    },
    {
      "name": "school_level",
      "dataType": "varchar"
    },
    {
      "name": "pseudo_section_id",
      "dataType": "varchar"
    }
  ],
  "llm_elementary_teachers": [
    {
      "name": "staff_id",
      "dataType": "int"
    },
    {
      "name": "teacher_number",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "email",
      "dataType": "varchar"
    },
    {
      "name": "room_number",
      "dataType": "varchar"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "low_grade",
      "dataType": "int"
    },
    {
      "name": "high_grade",
      "dataType": "int"
    },
    {
      "name": "grade_range",
      "dataType": "varchar"
    },
    {
      "name": "homeroom_student_count",
      "dataType": "int"
    }
  ],
  "llm_elpac_scores": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "language_fluency_code",
      "dataType": "varchar"
    },
    {
      "name": "language_fluency",
      "dataType": "varchar"
    },
    {
      "name": "is_english_learner",
      "dataType": "varchar",
      "exampleValues": [
        "Yes",
        "No",
        "RFEP"
      ]
    },
    {
      "name": "test_code",
      "dataType": "varchar"
    },
    {
      "name": "test_date",
      "dataType": "datetime"
    },
    {
      "name": "test_year",
      "dataType": "int"
    },
    {
      "name": "performance_level",
      "dataType": "decimal"
    },
    {
      "name": "scale_score",
      "dataType": "int"
    },
    {
      "name": "elpac_level_description",
      "dataType": "varchar"
    },
    {
      "name": "is_newcomer_el",
      "dataType": "varchar",
      "exampleValues": [
        "Yes",
        "No"
      ]
    },
    {
      "name": "is_long_term_el",
      "dataType": "varchar",
      "exampleValues": [
        "Yes",
        "No"
      ]
    },
    {
      "name": "us_school_entry_date",
      "dataType": "datetime"
    },
    {
      "name": "us_entry_date",
      "dataType": "datetime"
    },
    {
      "name": "birth_country",
      "dataType": "varchar"
    },
    {
      "name": "years_in_us_schools",
      "dataType": "int"
    }
  ],
  "llm_frpm_status": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "frpm_code",
      "dataType": "varchar"
    },
    {
      "name": "frpm_status",
      "dataType": "varchar"
    },
    {
      "name": "eligibility_code",
      "dataType": "varchar"
    },
    {
      "name": "eligibility_method",
      "dataType": "varchar"
    },
    {
      "name": "effective_start_date",
      "dataType": "datetime"
    },
    {
      "name": "is_frpm_eligible",
      "dataType": "int"
    },
    {
      "name": "is_free",
      "dataType": "int"
    },
    {
      "name": "is_reduced",
      "dataType": "int"
    }
  ],
  "llm_sed_status": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "frpm_code",
      "dataType": "varchar"
    },
    {
      "name": "is_frpm_eligible",
      "dataType": "int"
    },
    {
      "name": "lowest_parent_education_level",
      "dataType": "varchar"
    },
    {
      "name": "has_low_parent_education",
      "dataType": "int"
    },
    {
      "name": "direct_certification_flag",
      "dataType": "varchar",
      "exampleValues": [
        "3",
        "2",
        "6",
        "1",
        "5",
        "4"
      ]
    },
    {
      "name": "is_sed",
      "dataType": "int"
    },
    {
      "name": "sed_reason",
      "dataType": "varchar"
    }
  ],
  "llm_special_education": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "sped_status",
      "dataType": "varchar"
    },
    {
      "name": "eligibility_date",
      "dataType": "datetime"
    },
    {
      "name": "exit_date",
      "dataType": "datetime"
    },
    {
      "name": "placement_code",
      "dataType": "varchar"
    },
    {
      "name": "placement_description",
      "dataType": "varchar"
    },
    {
      "name": "primary_disability_code",
      "dataType": "varchar"
    },
    {
      "name": "primary_disability",
      "dataType": "varchar"
    },
    {
      "name": "last_assessment_date",
      "dataType": "datetime"
    },
    {
      "name": "assessment_date",
      "dataType": "datetime"
    },
    {
      "name": "review_date",
      "dataType": "datetime"
    },
    {
      "name": "is_active_sped",
      "dataType": "int"
    }
  ],
  "llm_special_programs": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "program_code",
      "dataType": "varchar"
    },
    {
      "name": "program_description",
      "dataType": "varchar"
    },
    {
      "name": "program_category",
      "dataType": "varchar"
    },
    {
      "name": "program_start_date",
      "dataType": "datetime"
    },
    {
      "name": "program_end_date",
      "dataType": "datetime"
    },
    {
      "name": "eligibility_start_date",
      "dataType": "datetime"
    },
    {
      "name": "eligibility_end_date",
      "dataType": "datetime"
    },
    {
      "name": "is_active",
      "dataType": "int"
    },
    {
      "name": "status",
      "dataType": "varchar"
    }
  ],
  "llm_staff_roster": [
    {
      "name": "staff_id",
      "dataType": "int"
    },
    {
      "name": "teacher_number",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "middle_name",
      "dataType": "varchar"
    },
    {
      "name": "email",
      "dataType": "varchar"
    },
    {
      "name": "room_number",
      "dataType": "varchar"
    },
    {
      "name": "low_grade",
      "dataType": "int"
    },
    {
      "name": "high_grade",
      "dataType": "int"
    },
    {
      "name": "grade_range",
      "dataType": "varchar"
    },
    {
      "name": "custom_field_1",
      "dataType": "varchar"
    },
    {
      "name": "custom_field_2",
      "dataType": "varchar"
    },
    {
      "name": "teacher_status",
      "dataType": "varchar"
    },
    {
      "name": "school_level",
      "dataType": "varchar"
    },
    {
      "name": "sections_taught",
      "dataType": "int"
    },
    {
      "name": "total_students",
      "dataType": "int"
    }
  ],
  "llm_student_contacts": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "student_last_name",
      "dataType": "varchar"
    },
    {
      "name": "student_first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "contact_sequence",
      "dataType": "int"
    },
    {
      "name": "contact_first_name",
      "dataType": "varchar"
    },
    {
      "name": "contact_last_name",
      "dataType": "varchar"
    },
    {
      "name": "relationship_code",
      "dataType": "varchar"
    },
    {
      "name": "relationship",
      "dataType": "varchar"
    },
    {
      "name": "email",
      "dataType": "varchar"
    },
    {
      "name": "home_phone",
      "dataType": "varchar"
    },
    {
      "name": "work_phone",
      "dataType": "varchar"
    },
    {
      "name": "cell_phone",
      "dataType": "varchar"
    },
    {
      "name": "address",
      "dataType": "varchar"
    },
    {
      "name": "city",
      "dataType": "varchar"
    },
    {
      "name": "state",
      "dataType": "varchar"
    },
    {
      "name": "zip_code",
      "dataType": "varchar"
    },
    {
      "name": "is_primary_contact",
      "dataType": "varchar",
      "exampleValues": [
        "Y",
        "",
        "N"
      ]
    },
    {
      "name": "lives_with_student",
      "dataType": "varchar",
      "exampleValues": [
        "Y",
        "",
        "N"
      ]
    },
    {
      "name": "notification_priority",
      "dataType": "varchar"
    },
    {
      "name": "notification_priority_description",
      "dataType": "varchar"
    },
    {
      "name": "education_level_code",
      "dataType": "varchar"
    },
    {
      "name": "education_level",
      "dataType": "varchar"
    }
  ],
  "llm_student_demographics": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "state_student_id",
      "dataType": "varchar"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "middle_name",
      "dataType": "varchar"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "birth_date",
      "dataType": "date"
    },
    {
      "name": "age",
      "dataType": "int"
    },
    {
      "name": "gender",
      "dataType": "varchar"
    },
    {
      "name": "address",
      "dataType": "varchar"
    },
    {
      "name": "city",
      "dataType": "varchar"
    },
    {
      "name": "state",
      "dataType": "varchar"
    },
    {
      "name": "zip_code",
      "dataType": "varchar"
    },
    {
      "name": "home_phone",
      "dataType": "varchar"
    },
    {
      "name": "parent_guardian_name",
      "dataType": "varchar"
    },
    {
      "name": "parent_email",
      "dataType": "varchar"
    },
    {
      "name": "student_email",
      "dataType": "varchar"
    },
    {
      "name": "home_language_code",
      "dataType": "varchar"
    },
    {
      "name": "home_language",
      "dataType": "varchar"
    },
    {
      "name": "correspondence_language_code",
      "dataType": "varchar"
    },
    {
      "name": "correspondence_language",
      "dataType": "varchar"
    },
    {
      "name": "language_fluency_code",
      "dataType": "varchar"
    },
    {
      "name": "language_fluency",
      "dataType": "varchar"
    },
    {
      "name": "english_learner_status",
      "dataType": "varchar"
    },
    {
      "name": "ethnicity_code",
      "dataType": "varchar"
    },
    {
      "name": "ethnicity",
      "dataType": "varchar"
    },
    {
      "name": "race_code_1",
      "dataType": "varchar"
    },
    {
      "name": "race_1",
      "dataType": "varchar"
    },
    {
      "name": "race_code_2",
      "dataType": "varchar"
    },
    {
      "name": "race_2",
      "dataType": "varchar"
    },
    {
      "name": "race_code_3",
      "dataType": "varchar"
    },
    {
      "name": "race_3",
      "dataType": "varchar"
    },
    {
      "name": "race_code_4",
      "dataType": "varchar"
    },
    {
      "name": "race_4",
      "dataType": "varchar"
    },
    {
      "name": "race_code_5",
      "dataType": "varchar"
    },
    {
      "name": "race_5",
      "dataType": "varchar"
    },
    {
      "name": "primary_race_ethnicity",
      "dataType": "varchar"
    },
    {
      "name": "birth_country_code",
      "dataType": "varchar"
    },
    {
      "name": "birth_city",
      "dataType": "varchar"
    },
    {
      "name": "birth_state",
      "dataType": "varchar"
    },
    {
      "name": "counselor_email",
      "dataType": "varchar"
    },
    {
      "name": "counselor_name",
      "dataType": "varchar"
    },
    {
      "name": "student_status_code",
      "dataType": "varchar"
    },
    {
      "name": "student_status",
      "dataType": "varchar"
    },
    {
      "name": "special_program_status",
      "dataType": "varchar"
    },
    {
      "name": "entry_date",
      "dataType": "datetime"
    },
    {
      "name": "leave_date",
      "dataType": "datetime"
    },
    {
      "name": "interdistrict_transfer_code",
      "dataType": "varchar"
    },
    {
      "name": "interdistrict_transfer_district",
      "dataType": "varchar"
    },
    {
      "name": "custom_field_u11",
      "dataType": "varchar"
    },
    {
      "name": "days_absent_ytd",
      "dataType": "int"
    },
    {
      "name": "days_enrolled_ytd",
      "dataType": "int"
    },
    {
      "name": "days_present_ytd",
      "dataType": "int"
    },
    {
      "name": "attendance_rate_ytd",
      "dataType": "float"
    }
  ],
  "llm_student_enrollment": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "school_year",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "entry_date",
      "dataType": "datetime"
    },
    {
      "name": "leave_date",
      "dataType": "datetime"
    },
    {
      "name": "enrollment_status",
      "dataType": "varchar"
    },
    {
      "name": "days_enrolled",
      "dataType": "int"
    },
    {
      "name": "grade_level_at_enrollment",
      "dataType": "int"
    },
    {
      "name": "entry_reason_code",
      "dataType": "varchar"
    },
    {
      "name": "entry_reason",
      "dataType": "varchar"
    },
    {
      "name": "homeroom_teacher_number",
      "dataType": "int"
    },
    {
      "name": "homeroom_teacher_name",
      "dataType": "varchar"
    },
    {
      "name": "homeroom_teacher_email",
      "dataType": "varchar"
    },
    {
      "name": "track",
      "dataType": "varchar"
    },
    {
      "name": "program",
      "dataType": "varchar"
    },
    {
      "name": "is_current_year",
      "dataType": "int"
    }
  ],
  "llm_student_gpa": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "current_gpa",
      "dataType": "decimal"
    },
    {
      "name": "cumulative_credits",
      "dataType": "int"
    },
    {
      "name": "current_year_credits",
      "dataType": "decimal"
    },
    {
      "name": "failing_grade_count",
      "dataType": "int"
    },
    {
      "name": "at_risk_grade_count",
      "dataType": "int"
    },
    {
      "name": "honor_grade_count",
      "dataType": "int"
    },
    {
      "name": "academic_standing",
      "dataType": "varchar"
    },
    {
      "name": "academic_risk_level",
      "dataType": "varchar"
    }
  ],
  "llm_student_grades": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "section_number",
      "dataType": "int"
    },
    {
      "name": "course_number",
      "dataType": "varchar"
    },
    {
      "name": "period",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "course_name",
      "dataType": "varchar"
    },
    {
      "name": "course_description",
      "dataType": "varchar"
    },
    {
      "name": "department_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_last_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_first_name",
      "dataType": "varchar"
    },
    {
      "name": "final_grade",
      "dataType": "varchar"
    },
    {
      "name": "credits_earned",
      "dataType": "decimal"
    },
    {
      "name": "mark_1",
      "dataType": "varchar"
    },
    {
      "name": "mark_2",
      "dataType": "varchar"
    },
    {
      "name": "mark_3",
      "dataType": "varchar"
    },
    {
      "name": "mark_4",
      "dataType": "varchar"
    },
    {
      "name": "mark_5",
      "dataType": "varchar"
    },
    {
      "name": "mark_6",
      "dataType": "varchar"
    },
    {
      "name": "citizenship_1",
      "dataType": "varchar"
    },
    {
      "name": "citizenship_2",
      "dataType": "varchar"
    },
    {
      "name": "citizenship_3",
      "dataType": "varchar"
    },
    {
      "name": "citizenship_indicator",
      "dataType": "varchar"
    },
    {
      "name": "grade_comments",
      "dataType": "varchar"
    },
    {
      "name": "is_failing",
      "dataType": "int"
    },
    {
      "name": "is_honor_grade",
      "dataType": "int"
    },
    {
      "name": "is_at_risk",
      "dataType": "int"
    }
  ],
  "llm_student_program_summary": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "is_english_learner",
      "dataType": "int"
    },
    {
      "name": "language_fluency_code",
      "dataType": "varchar"
    },
    {
      "name": "language_fluency",
      "dataType": "varchar"
    },
    {
      "name": "is_special_education",
      "dataType": "int"
    },
    {
      "name": "sped_disability_code",
      "dataType": "varchar"
    },
    {
      "name": "sped_primary_disability",
      "dataType": "varchar"
    },
    {
      "name": "is_foster_youth",
      "dataType": "int"
    },
    {
      "name": "is_homeless",
      "dataType": "int"
    },
    {
      "name": "is_migrant",
      "dataType": "int"
    },
    {
      "name": "is_section_504",
      "dataType": "int"
    },
    {
      "name": "is_in_any_special_program",
      "dataType": "int"
    }
  ],
  "llm_suspension_summary": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "out_of_school_suspensions",
      "dataType": "int"
    },
    {
      "name": "in_school_suspensions",
      "dataType": "int"
    },
    {
      "name": "total_suspensions",
      "dataType": "int"
    },
    {
      "name": "expulsions",
      "dataType": "int"
    },
    {
      "name": "most_recent_suspension_date",
      "dataType": "date"
    },
    {
      "name": "first_suspension_date",
      "dataType": "date"
    },
    {
      "name": "days_since_last_suspension",
      "dataType": "int"
    },
    {
      "name": "discipline_risk_level",
      "dataType": "varchar"
    }
  ],
  "llm_teacher_courses": [
    {
      "name": "staff_id",
      "dataType": "int"
    },
    {
      "name": "teacher_number",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "teacher_last_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_first_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_email",
      "dataType": "varchar"
    },
    {
      "name": "teacher_room",
      "dataType": "varchar"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "section_number",
      "dataType": "int"
    },
    {
      "name": "period",
      "dataType": "int"
    },
    {
      "name": "section_room",
      "dataType": "varchar"
    },
    {
      "name": "course_number",
      "dataType": "varchar"
    },
    {
      "name": "course_name",
      "dataType": "varchar"
    },
    {
      "name": "course_description",
      "dataType": "varchar"
    },
    {
      "name": "department_code",
      "dataType": "varchar"
    },
    {
      "name": "department_name",
      "dataType": "varchar"
    },
    {
      "name": "schedule_mode",
      "dataType": "varchar"
    },
    {
      "name": "schedule_mode_description",
      "dataType": "varchar"
    },
    {
      "name": "current_enrollment",
      "dataType": "int"
    },
    {
      "name": "credits",
      "dataType": "decimal"
    },
    {
      "name": "state_course_code",
      "dataType": "int"
    }
  ],
  "llm_teacher_student_roster": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "teacher_staff_id",
      "dataType": "int"
    },
    {
      "name": "teacher_number",
      "dataType": "int"
    },
    {
      "name": "teacher_last_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_first_name",
      "dataType": "varchar"
    },
    {
      "name": "teacher_email",
      "dataType": "varchar"
    },
    {
      "name": "assignment_type",
      "dataType": "varchar"
    },
    {
      "name": "section_number",
      "dataType": "int"
    },
    {
      "name": "course_name",
      "dataType": "varchar"
    },
    {
      "name": "period",
      "dataType": "int"
    },
    {
      "name": "teacher_section_id",
      "dataType": "varchar"
    }
  ],
  "llm_test_scores": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "test_code",
      "dataType": "varchar"
    },
    {
      "name": "test_description",
      "dataType": "varchar"
    },
    {
      "name": "test_date",
      "dataType": "datetime"
    },
    {
      "name": "test_year",
      "dataType": "int"
    },
    {
      "name": "test_type",
      "dataType": "varchar"
    },
    {
      "name": "test_category",
      "dataType": "varchar"
    },
    {
      "name": "performance_level",
      "dataType": "decimal"
    },
    {
      "name": "scale_score",
      "dataType": "int"
    },
    {
      "name": "raw_score",
      "dataType": "int"
    },
    {
      "name": "elpac_level_description",
      "dataType": "varchar"
    },
    {
      "name": "caaspp_level_description",
      "dataType": "varchar"
    },
    {
      "name": "part_type",
      "dataType": "int"
    },
    {
      "name": "part_description",
      "dataType": "varchar"
    },
    {
      "name": "grade_at_test",
      "dataType": "int"
    },
    {
      "name": "recency_rank",
      "dataType": "int"
    }
  ],
  "llm_test_scores_current": [
    {
      "name": "student_id",
      "dataType": "int"
    },
    {
      "name": "school_id",
      "dataType": "int"
    },
    {
      "name": "student_number",
      "dataType": "int"
    },
    {
      "name": "last_name",
      "dataType": "varchar"
    },
    {
      "name": "first_name",
      "dataType": "varchar"
    },
    {
      "name": "grade_level",
      "dataType": "int"
    },
    {
      "name": "school_name",
      "dataType": "varchar"
    },
    {
      "name": "test_code",
      "dataType": "varchar"
    },
    {
      "name": "test_description",
      "dataType": "varchar"
    },
    {
      "name": "test_date",
      "dataType": "datetime"
    },
    {
      "name": "test_year",
      "dataType": "int"
    },
    {
      "name": "test_category",
      "dataType": "varchar"
    },
    {
      "name": "performance_level",
      "dataType": "decimal"
    },
    {
      "name": "scale_score",
      "dataType": "int"
    },
    {
      "name": "raw_score",
      "dataType": "int"
    },
    {
      "name": "elpac_level_description",
      "dataType": "varchar"
    },
    {
      "name": "caaspp_level_description",
      "dataType": "varchar"
    },
    {
      "name": "part_type",
      "dataType": "int"
    },
    {
      "name": "part_description",
      "dataType": "varchar"
    },
    {
      "name": "grade_at_test",
      "dataType": "int"
    }
  ]
};
