/**
 * Generates lib/ai-query/view-schema.generated.ts from the live Aeries MSSQL
 * database by introspecting INFORMATION_SCHEMA for the llm_* views.
 *
 * The generated file is the single source of truth for:
 *   - the sql-validator whitelist (allowed views + columns + bit columns)
 *   - the per-view column listings in the LLM system prompt
 *
 * Run whenever the llm_* views change:
 *   npm run generate:view-schema
 *   npx tsx scripts/generate-view-schema.ts --dbYear=25
 *
 * Connects directly with env DB_USER / DB_PASSWORD / DB_SERVER (same as
 * lib/aeries.ts - not imported because that module is "use server" and does
 * not export its pool helper).
 */

import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import mssql from 'mssql';
import { AVAILABLE_DB_YEARS, getDatabaseName } from '../lib/schoolYear';

function parseArgs() {
  const arg = process.argv.find((a) => a.startsWith('--dbYear='));
  return { dbYear: arg ? parseInt(arg.split('=')[1]) : AVAILABLE_DB_YEARS[0].year };
}

async function main() {
  const { dbYear } = parseArgs();
  const database = getDatabaseName(dbYear);
  console.log(`Introspecting llm_* views in ${database}...`);

  const pool = await new mssql.ConnectionPool({
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    server: process.env.DB_SERVER!,
    database,
    options: { encrypt: true, trustServerCertificate: true },
    connectionTimeout: 30000,
    requestTimeout: 60000,
  }).connect();

  const result = await pool.request().query(`
    SELECT c.TABLE_NAME, c.COLUMN_NAME, c.DATA_TYPE, c.ORDINAL_POSITION
    FROM INFORMATION_SCHEMA.COLUMNS c
    JOIN INFORMATION_SCHEMA.VIEWS v
      ON v.TABLE_NAME = c.TABLE_NAME AND v.TABLE_SCHEMA = c.TABLE_SCHEMA
    WHERE c.TABLE_NAME LIKE 'llm[_]%'
    ORDER BY c.TABLE_NAME, c.ORDINAL_POSITION
  `);

  await pool.close();

  const rows = result.recordset as { TABLE_NAME: string; COLUMN_NAME: string; DATA_TYPE: string }[];
  if (rows.length === 0) {
    console.error('No llm_* views found - aborting without writing.');
    process.exit(1);
  }

  // Normalize SQL Server type names to the compact set used in prompts/validation
  const normalizeType = (t: string): string => {
    const type = t.toLowerCase();
    if (['nvarchar', 'varchar', 'char', 'nchar', 'text', 'ntext'].includes(type)) return 'varchar';
    if (['smallint', 'tinyint', 'bigint'].includes(type)) return 'int';
    if (['numeric', 'money', 'smallmoney'].includes(type)) return 'decimal';
    if (['real'].includes(type)) return 'float';
    if (['datetime', 'datetime2', 'smalldatetime'].includes(type)) return 'datetime';
    return type; // bit, int, decimal, float, date, time, uniqueidentifier, ...
  };

  const schemas: Record<string, { name: string; dataType: string; exampleValues?: string[] }[]> = {};
  for (const row of rows) {
    const view = row.TABLE_NAME.toLowerCase();
    (schemas[view] ??= []).push({
      name: row.COLUMN_NAME.toLowerCase(),
      dataType: normalizeType(row.DATA_TYPE),
    });
  }

  // Flag-named columns are NOT consistently typed in the views: some are
  // int 0/1, others are varchar 'Yes'/'No' or 'Y'/'N' (and elpac's
  // is_english_learner even holds 'RFEP'). Sample the actual values of
  // text-typed flags so the prompt and validator can state the truth.
  const FLAG_NAME = /^(is_|has_)|^(lives_with_student|was_absent_all_day|all_day_counts_as_present|all_day_suspension_related|direct_certification_flag)$/;
  const samplePool = await new mssql.ConnectionPool({
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    server: process.env.DB_SERVER!,
    database,
    options: { encrypt: true, trustServerCertificate: true },
    connectionTimeout: 30000,
    requestTimeout: 60000,
  }).connect();

  for (const [view, cols] of Object.entries(schemas)) {
    for (const col of cols) {
      if (col.dataType !== 'varchar' || !FLAG_NAME.test(col.name)) continue;
      try {
        const sample = await samplePool.request().query(
          `SELECT DISTINCT TOP 8 [${col.name}] AS v FROM [${view}]`
        );
        col.exampleValues = sample.recordset
          .map((r: { v: unknown }) => (r.v === null ? null : String(r.v)))
          .filter((v: string | null): v is string => v !== null);
        console.log(`  sampled ${view}.${col.name}: ${col.exampleValues.map((v) => `'${v}'`).join(', ')}`);
      } catch (err) {
        console.warn(`  could not sample ${view}.${col.name}:`, err instanceof Error ? err.message : err);
      }
    }
  }
  await samplePool.close();

  const viewCount = Object.keys(schemas).length;
  const columnCount = rows.length;

  const header = `/**
 * AUTO-GENERATED by scripts/generate-view-schema.ts - DO NOT EDIT BY HAND.
 *
 * Source: INFORMATION_SCHEMA of ${database}
 * Views: ${viewCount}, columns: ${columnCount}
 *
 * Regenerate with: npm run generate:view-schema
 */

export interface ViewColumn {
  name: string;
  dataType: string;
  /** Sampled distinct values for text-typed flag columns (e.g. 'Yes'/'No') */
  exampleValues?: string[];
}

export const VIEW_SCHEMAS: Record<string, ViewColumn[]> = `;

  const body = JSON.stringify(schemas, null, 2);

  const scriptDir = path.dirname(fileURLToPath(import.meta.url));
  const outPath = path.join(scriptDir, '..', 'lib', 'ai-query', 'view-schema.generated.ts');
  fs.writeFileSync(outPath, `${header}${body};\n`);

  console.log(`Wrote ${viewCount} views / ${columnCount} columns to ${outPath}`);
  for (const [view, cols] of Object.entries(schemas)) {
    console.log(`  ${view} (${cols.length} columns)`);
  }
}

main().then(() => process.exit(0)).catch((err) => {
  console.error(err);
  process.exit(1);
});
