export const initialData = [
    {
      SC: 12,
      TN: 4,
      TLN: "Achten",
      TF: "Jennifer",
      Teacher: "Jennifer Achten",
      Department: "ELD",
      Term: "PRG2",
      A: 0,
      B: 0,
      C: 7,
      D: 5,
      F: 8,
      Other: 0,
      Total_Marks: 20,
      "A%": 0,
      "B%": 0,
      "C%": 35,
      "D%": 25,
      "F%": 40,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 4,
      TLN: "Achten",
      TF: "Jennifer",
      Teacher: "Jennifer Achten",
      Department: "ELD",
      Term: "PRG3",
      A: 0,
      B: 0,
      C: 10,
      D: 4,
      F: 8,
      Other: 0,
      Total_Marks: 22,
      "A%": 0,
      "B%": 0,
      "C%": 45.5,
      "D%": 18.2,
      "F%": 36.4,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 95,
      TLN: "Rocco",
      TF: "Kendra",
      Teacher: "Kendra Rocco",
      Department: "ELD",
      Term: "PRG1",
      A: 5,
      B: 1,
      C: 1,
      D: 3,
      F: 4,
      Other: 0,
      Total_Marks: 14,
      "A%": 35.7,
      "B%": 7.1,
      "C%": 7.1,
      "D%": 21.4,
      "F%": 28.6,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 85,
      TLN: "Sherman",
      TF: "Samantha",
      Teacher: "Samantha Sherman",
      Department: "ELD",
      Term: "GRD1",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 3,
      Other: 7,
      Total_Marks: 11,
      "A%": 9.1,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 27.3,
      Other_Percent: 63.6,
     },
   {
      SC: 12,
      TN: 4,
      TLN: "Achten",
      TF: "Jennifer",
      Teacher: "Jennifer Achten",
      Department: "ELD",
      Term: "PRG1",
      A: 0,
      B: 0,
      C: 11,
      D: 4,
      F: 3,
      Other: 0,
      Total_Marks: 18,
      "A%": 0,
      "B%": 0,
      "C%": 61.1,
      "D%": 22.2,
      "F%": 16.7,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 4,
      TLN: "Achten",
      TF: "Jennifer",
      Teacher: "Jennifer Achten",
      Department: "ELD",
      Term: "GRD2",
      A: 6,
      B: 15,
      C: 11,
      D: 1,
      F: 4,
      Other: 1,
      Total_Marks: 38,
      "A%": 15.8,
      "B%": 39.5,
      "C%": 28.9,
      "D%": 2.6,
      "F%": 10.5,
      Other_Percent: 2.6,
     },
   {
      SC: 12,
      TN: 95,
      TLN: "Rocco",
      TF: "Kendra",
      Teacher: "Kendra Rocco",
      Department: "ELD",
      Term: "PRG2",
      A: 1,
      B: 5,
      C: 2,
      D: 4,
      F: 1,
      Other: 0,
      Total_Marks: 13,
      "A%": 7.7,
      "B%": 38.5,
      "C%": 15.4,
      "D%": 30.8,
      "F%": 7.7,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 95,
      TLN: "Rocco",
      TF: "Kendra",
      Teacher: "Kendra Rocco",
      Department: "ELD",
      Term: "GRD1",
      A: 5,
      B: 2,
      C: 4,
      D: 2,
      F: 1,
      Other: 0,
      Total_Marks: 14,
      "A%": 35.7,
      "B%": 14.3,
      "C%": 28.6,
      "D%": 14.3,
      "F%": 7.1,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 818,
      TLN: "Stein",
      TF: "Sarah",
      Teacher: "Sarah Stein",
      Department: "ELD",
      Term: "GRD1",
      A: 2,
      B: 14,
      C: 5,
      D: 2,
      F: 1,
      Other: 0,
      Total_Marks: 24,
      "A%": 8.3,
      "B%": 58.3,
      "C%": 20.8,
      "D%": 8.3,
      "F%": 4.2,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 818,
      TLN: "Stein",
      TF: "Sarah",
      Teacher: "Sarah Stein",
      Department: "ELD",
      Term: "GRD2",
      A: 0,
      B: 15,
      C: 6,
      D: 2,
      F: 1,
      Other: 0,
      Total_Marks: 24,
      "A%": 0,
      "B%": 62.5,
      "C%": 25,
      "D%": 8.3,
      "F%": 4.2,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 818,
      TLN: "Stein",
      TF: "Sarah",
      Teacher: "Sarah Stein",
      Department: "ELD",
      Term: "PRG2",
      A: 0,
      B: 10,
      C: 12,
      D: 1,
      F: 1,
      Other: 0,
      Total_Marks: 24,
      "A%": 0,
      "B%": 41.7,
      "C%": 50,
      "D%": 4.2,
      "F%": 4.2,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 4,
      TLN: "Achten",
      TF: "Jennifer",
      Teacher: "Jennifer Achten",
      Department: "ELD",
      Term: "GRD1",
      A: 5,
      B: 11,
      C: 11,
      D: 5,
      F: 1,
      Other: 0,
      Total_Marks: 33,
      "A%": 15.2,
      "B%": 33.3,
      "C%": 33.3,
      "D%": 15.2,
      "F%": 3,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 113,
      TLN: "Morris",
      TF: "Kellie",
      Teacher: "Kellie Morris",
      Department: "ELD",
      Term: "PRG2",
      A: 0,
      B: 0,
      C: 1,
      D: 1,
      F: 0,
      Other: 0,
      Total_Marks: 2,
      "A%": 0,
      "B%": 0,
      "C%": 50,
      "D%": 50,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 818,
      TLN: "Stein",
      TF: "Sarah",
      Teacher: "Sarah Stein",
      Department: "ELD",
      Term: "PRG3",
      A: 1,
      B: 9,
      C: 10,
      D: 3,
      F: 0,
      Other: 0,
      Total_Marks: 23,
      "A%": 4.3,
      "B%": 39.1,
      "C%": 43.5,
      "D%": 13,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 818,
      TLN: "Stein",
      TF: "Sarah",
      Teacher: "Sarah Stein",
      Department: "ELD",
      Term: "PRG1",
      A: 1,
      B: 10,
      C: 10,
      D: 3,
      F: 0,
      Other: 0,
      Total_Marks: 24,
      "A%": 4.2,
      "B%": 41.7,
      "C%": 41.7,
      "D%": 12.5,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 76,
      TLN: "Zehnder",
      TF: "Sara",
      Teacher: "Sara Zehnder",
      Department: "ELD",
      Term: "GRD1",
      A: 2,
      B: 13,
      C: 2,
      D: 1,
      F: 0,
      Other: 0,
      Total_Marks: 18,
      "A%": 11.1,
      "B%": 72.2,
      "C%": 11.1,
      "D%": 5.6,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 76,
      TLN: "Zehnder",
      TF: "Sara",
      Teacher: "Sara Zehnder",
      Department: "ELD",
      Term: "GRD2",
      A: 12,
      B: 6,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 18,
      "A%": 66.7,
      "B%": 33.3,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 76,
      TLN: "Zehnder",
      TF: "Sara",
      Teacher: "Sara Zehnder",
      Department: "ELD",
      Term: "PRG2",
      A: 8,
      B: 10,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 18,
      "A%": 44.4,
      "B%": 55.6,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 85,
      TLN: "Sherman",
      TF: "Samantha",
      Teacher: "Samantha Sherman",
      Department: "ELD",
      Term: "GRD2",
      A: 0,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 10,
      Total_Marks: 10,
      "A%": 0,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 100,
     },
   {
      SC: 12,
      TN: 95,
      TLN: "Rocco",
      TF: "Kendra",
      Teacher: "Kendra Rocco",
      Department: "ELD",
      Term: "GRD2",
      A: 2,
      B: 7,
      C: 3,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 12,
      "A%": 16.7,
      "B%": 58.3,
      "C%": 25,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 113,
      TLN: "Morris",
      TF: "Kellie",
      Teacher: "Kellie Morris",
      Department: "ELD",
      Term: "PRG3",
      A: 0,
      B: 0,
      C: 1,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 0,
      "B%": 0,
      "C%": 100,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 113,
      TLN: "Morris",
      TF: "Kellie",
      Teacher: "Kellie Morris",
      Department: "ELD",
      Term: "GRD1",
      A: 0,
      B: 10,
      C: 8,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 18,
      "A%": 0,
      "B%": 55.6,
      "C%": 44.4,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 113,
      TLN: "Morris",
      TF: "Kellie",
      Teacher: "Kellie Morris",
      Department: "ELD",
      Term: "GRD2",
      A: 2,
      B: 10,
      C: 5,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 17,
      "A%": 11.8,
      "B%": 58.8,
      "C%": 29.4,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 113,
      TLN: "Morris",
      TF: "Kellie",
      Teacher: "Kellie Morris",
      Department: "ELD",
      Term: "PRG1",
      A: 4,
      B: 8,
      C: 6,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 18,
      "A%": 22.2,
      "B%": 44.4,
      "C%": 33.3,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 4,
      TLN: "Achten",
      TF: "Jennifer",
      Teacher: "Jennifer Achten",
      Department: "Elective (MS only)",
      Term: "PRG3",
      A: 0,
      B: 0,
      C: 5,
      D: 3,
      F: 11,
      Other: 0,
      Total_Marks: 19,
      "A%": 0,
      "B%": 0,
      "C%": 26.3,
      "D%": 15.8,
      "F%": 57.9,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 4,
      TLN: "Achten",
      TF: "Jennifer",
      Teacher: "Jennifer Achten",
      Department: "Elective (MS only)",
      Term: "PRG2",
      A: 0,
      B: 0,
      C: 3,
      D: 3,
      F: 4,
      Other: 0,
      Total_Marks: 10,
      "A%": 0,
      "B%": 0,
      "C%": 30,
      "D%": 30,
      "F%": 40,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 71,
      TLN: "Setka",
      TF: "Kristina",
      Teacher: "Kristina Setka",
      Department: "Elective (MS only)",
      Term: "PRG1",
      A: 64,
      B: 33,
      C: 12,
      D: 1,
      F: 16,
      Other: 0,
      Total_Marks: 126,
      "A%": 50.8,
      "B%": 26.2,
      "C%": 9.5,
      "D%": 0.8,
      "F%": 12.7,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 78,
      TLN: "King",
      TF: "Tarri",
      Teacher: "Tarri King",
      Department: "Elective (MS only)",
      Term: "PRG2",
      A: 18,
      B: 7,
      C: 0,
      D: 1,
      F: 3,
      Other: 0,
      Total_Marks: 29,
      "A%": 62.1,
      "B%": 24.1,
      "C%": 0,
      "D%": 3.4,
      "F%": 10.3,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 6,
      TLN: "Belli",
      TF: "Michael",
      Teacher: "Michael Belli",
      Department: "Elective (MS only)",
      Term: "PRG3",
      A: 16,
      B: 6,
      C: 3,
      D: 1,
      F: 2,
      Other: 0,
      Total_Marks: 28,
      "A%": 57.1,
      "B%": 21.4,
      "C%": 10.7,
      "D%": 3.6,
      "F%": 7.1,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 71,
      TLN: "Setka",
      TF: "Kristina",
      Teacher: "Kristina Setka",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 76,
      B: 17,
      C: 13,
      D: 15,
      F: 6,
      Other: 0,
      Total_Marks: 127,
      "A%": 59.8,
      "B%": 13.4,
      "C%": 10.2,
      "D%": 11.8,
      "F%": 4.7,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 929,
      TLN: "Wong",
      TF: "Thea",
      Teacher: "Thea Wong",
      Department: "Elective (MS only)",
      Term: "PRG1",
      A: 8,
      B: 15,
      C: 7,
      D: 0,
      F: 1,
      Other: 0,
      Total_Marks: 31,
      "A%": 25.8,
      "B%": 48.4,
      "C%": 22.6,
      "D%": 0,
      "F%": 3.2,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 43,
      TLN: "Griffith",
      TF: "Zachary",
      Teacher: "Zachary Griffith",
      Department: "Elective (MS only)",
      Term: "PRG1",
      A: 32,
      B: 1,
      C: 0,
      D: 0,
      F: 1,
      Other: 0,
      Total_Marks: 34,
      "A%": 94.1,
      "B%": 2.9,
      "C%": 0,
      "D%": 0,
      "F%": 2.9,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 65,
      TLN: "Lopez",
      TF: "Alfredo",
      Teacher: "Alfredo Lopez",
      Department: "Elective (MS only)",
      Term: "PRG3",
      A: 0,
      B: 0,
      C: 4,
      D: 2,
      F: 0,
      Other: 0,
      Total_Marks: 6,
      "A%": 0,
      "B%": 0,
      "C%": 66.7,
      "D%": 33.3,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 4,
      TLN: "Achten",
      TF: "Jennifer",
      Teacher: "Jennifer Achten",
      Department: "Elective (MS only)",
      Term: "PRG1",
      A: 0,
      B: 0,
      C: 7,
      D: 2,
      F: 0,
      Other: 0,
      Total_Marks: 9,
      "A%": 0,
      "B%": 0,
      "C%": 77.8,
      "D%": 22.2,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 6,
      TLN: "Belli",
      TF: "Michael",
      Teacher: "Michael Belli",
      Department: "Elective (MS only)",
      Term: "PRG1",
      A: 12,
      B: 5,
      C: 5,
      D: 5,
      F: 0,
      Other: 0,
      Total_Marks: 27,
      "A%": 44.4,
      "B%": 18.5,
      "C%": 18.5,
      "D%": 18.5,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 4,
      TLN: "Achten",
      TF: "Jennifer",
      Teacher: "Jennifer Achten",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 30,
      B: 4,
      C: 6,
      D: 6,
      F: 0,
      Other: 0,
      Total_Marks: 46,
      "A%": 65.2,
      "B%": 8.7,
      "C%": 13,
      "D%": 13,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 6,
      TLN: "Belli",
      TF: "Michael",
      Teacher: "Michael Belli",
      Department: "Elective (MS only)",
      Term: "PRG2",
      A: 19,
      B: 3,
      C: 4,
      D: 3,
      F: 0,
      Other: 0,
      Total_Marks: 29,
      "A%": 65.5,
      "B%": 10.3,
      "C%": 13.8,
      "D%": 10.3,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 78,
      TLN: "King",
      TF: "Tarri",
      Teacher: "Tarri King",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 6,
      B: 15,
      C: 5,
      D: 1,
      F: 0,
      Other: 0,
      Total_Marks: 27,
      "A%": 22.2,
      "B%": 55.6,
      "C%": 18.5,
      "D%": 3.7,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 78,
      TLN: "King",
      TF: "Tarri",
      Teacher: "Tarri King",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 8,
      B: 9,
      C: 11,
      D: 1,
      F: 0,
      Other: 0,
      Total_Marks: 29,
      "A%": 27.6,
      "B%": 31,
      "C%": 37.9,
      "D%": 3.4,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 43,
      TLN: "Griffith",
      TF: "Zachary",
      Teacher: "Zachary Griffith",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 29,
      B: 4,
      C: 1,
      D: 1,
      F: 0,
      Other: 0,
      Total_Marks: 35,
      "A%": 82.9,
      "B%": 11.4,
      "C%": 2.9,
      "D%": 2.9,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 43,
      TLN: "Griffith",
      TF: "Zachary",
      Teacher: "Zachary Griffith",
      Department: "Elective (MS only)",
      Term: "PRG2",
      A: 27,
      B: 5,
      C: 2,
      D: 1,
      F: 0,
      Other: 0,
      Total_Marks: 35,
      "A%": 77.1,
      "B%": 14.3,
      "C%": 5.7,
      "D%": 2.9,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 4,
      TLN: "Achten",
      TF: "Jennifer",
      Teacher: "Jennifer Achten",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 31,
      B: 14,
      C: 5,
      D: 1,
      F: 0,
      Other: 0,
      Total_Marks: 51,
      "A%": 60.8,
      "B%": 27.5,
      "C%": 9.8,
      "D%": 2,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 65,
      TLN: "Lopez",
      TF: "Alfredo",
      Teacher: "Alfredo Lopez",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 107,
      B: 30,
      C: 9,
      D: 1,
      F: 0,
      Other: 0,
      Total_Marks: 147,
      "A%": 72.8,
      "B%": 20.4,
      "C%": 6.1,
      "D%": 0.7,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 929,
      TLN: "Wong",
      TF: "Thea",
      Teacher: "Thea Wong",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 14,
      B: 15,
      C: 0,
      D: 0,
      F: 0,
      Other: 1,
      Total_Marks: 30,
      "A%": 46.7,
      "B%": 50,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 3.3,
     },
   {
      SC: 12,
      TN: 929,
      TLN: "Wong",
      TF: "Thea",
      Teacher: "Thea Wong",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 16,
      B: 9,
      C: 4,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 29,
      "A%": 55.2,
      "B%": 31,
      "C%": 13.8,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 929,
      TLN: "Wong",
      TF: "Thea",
      Teacher: "Thea Wong",
      Department: "Elective (MS only)",
      Term: "PRG2",
      A: 14,
      B: 12,
      C: 3,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 29,
      "A%": 48.3,
      "B%": 41.4,
      "C%": 10.3,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 51,
      TLN: "Toledo",
      TF: "Adela",
      Teacher: "Adela Toledo",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 51,
      TLN: "Toledo",
      TF: "Adela",
      Teacher: "Adela Toledo",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 51,
      TLN: "Toledo",
      TF: "Adela",
      Teacher: "Adela Toledo",
      Department: "Elective (MS only)",
      Term: "PRG1",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 81,
      TLN: "Tang",
      TF: "Jie",
      Teacher: "Jie Tang",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 17,
      B: 11,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 28,
      "A%": 60.7,
      "B%": 39.3,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 81,
      TLN: "Tang",
      TF: "Jie",
      Teacher: "Jie Tang",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 27,
      B: 2,
      C: 1,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 30,
      "A%": 90,
      "B%": 6.7,
      "C%": 3.3,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 71,
      TLN: "Setka",
      TF: "Kristina",
      Teacher: "Kristina Setka",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 125,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 125,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 69,
      TLN: "Patterson",
      TF: "Cj",
      Teacher: "Cj Patterson",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 11,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 11,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 69,
      TLN: "Patterson",
      TF: "Cj",
      Teacher: "Cj Patterson",
      Department: "Elective (MS only)",
      Term: "PRG3",
      A: 12,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 12,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 97,
      TLN: "Miller",
      TF: "Elizabeth",
      Teacher: "Elizabeth Miller",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 97,
      TLN: "Miller",
      TF: "Elizabeth",
      Teacher: "Elizabeth Miller",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 97,
      TLN: "Miller",
      TF: "Elizabeth",
      Teacher: "Elizabeth Miller",
      Department: "Elective (MS only)",
      Term: "PRG1",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 97,
      TLN: "Miller",
      TF: "Elizabeth",
      Teacher: "Elizabeth Miller",
      Department: "Elective (MS only)",
      Term: "PRG2",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 97,
      TLN: "Miller",
      TF: "Elizabeth",
      Teacher: "Elizabeth Miller",
      Department: "Elective (MS only)",
      Term: "PRG3",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 65,
      TLN: "Lopez",
      TF: "Alfredo",
      Teacher: "Alfredo Lopez",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 85,
      B: 50,
      C: 15,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 150,
      "A%": 56.7,
      "B%": 33.3,
      "C%": 10,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 43,
      TLN: "Griffith",
      TF: "Zachary",
      Teacher: "Zachary Griffith",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 33,
      B: 1,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 34,
      "A%": 97.1,
      "B%": 2.9,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 60,
      TLN: "Fong",
      TF: "Danny",
      Teacher: "Danny Fong",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 60,
      TLN: "Fong",
      TF: "Danny",
      Teacher: "Danny Fong",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 60,
      TLN: "Fong",
      TF: "Danny",
      Teacher: "Danny Fong",
      Department: "Elective (MS only)",
      Term: "PRG2",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 60,
      TLN: "Fong",
      TF: "Danny",
      Teacher: "Danny Fong",
      Department: "Elective (MS only)",
      Term: "PRG3",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 22,
      TLN: "Felarca",
      TF: "Devanie",
      Teacher: "Devanie Felarca",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 22,
      TLN: "Felarca",
      TF: "Devanie",
      Teacher: "Devanie Felarca",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 22,
      TLN: "Felarca",
      TF: "Devanie",
      Teacher: "Devanie Felarca",
      Department: "Elective (MS only)",
      Term: "PRG2",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 22,
      TLN: "Felarca",
      TF: "Devanie",
      Teacher: "Devanie Felarca",
      Department: "Elective (MS only)",
      Term: "PRG3",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 32,
      TLN: "Farrell",
      TF: "Denise",
      Teacher: "Denise Farrell",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 20,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 20,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 32,
      TLN: "Farrell",
      TF: "Denise",
      Teacher: "Denise Farrell",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 19,
      B: 1,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 20,
      "A%": 95,
      "B%": 5,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 939,
      TLN: "DeVera",
      TF: "Arcy",
      Teacher: "Arcy DeVera",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 36,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 36,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 939,
      TLN: "DeVera",
      TF: "Arcy",
      Teacher: "Arcy DeVera",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 36,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 36,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 822,
      TLN: "Carrillo",
      TF: "Refugio",
      Teacher: "Refugio Carrillo",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 63,
      TLN: "Carrillo",
      TF: "Carlos",
      Teacher: "Carlos Carrillo",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 63,
      TLN: "Carrillo",
      TF: "Carlos",
      Teacher: "Carlos Carrillo",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 63,
      TLN: "Carrillo",
      TF: "Carlos",
      Teacher: "Carlos Carrillo",
      Department: "Elective (MS only)",
      Term: "PRG1",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 63,
      TLN: "Carrillo",
      TF: "Carlos",
      Teacher: "Carlos Carrillo",
      Department: "Elective (MS only)",
      Term: "PRG2",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 63,
      TLN: "Carrillo",
      TF: "Carlos",
      Teacher: "Carlos Carrillo",
      Department: "Elective (MS only)",
      Term: "PRG3",
      A: 1,
      B: 0,
      C: 0,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 1,
      "A%": 100,
      "B%": 0,
      "C%": 0,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 6,
      TLN: "Belli",
      TF: "Michael",
      Teacher: "Michael Belli",
      Department: "Elective (MS only)",
      Term: "GRD1",
      A: 15,
      B: 12,
      C: 2,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 29,
      "A%": 51.7,
      "B%": 41.4,
      "C%": 6.9,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 6,
      TLN: "Belli",
      TF: "Michael",
      Teacher: "Michael Belli",
      Department: "Elective (MS only)",
      Term: "GRD2",
      A: 18,
      B: 9,
      C: 3,
      D: 0,
      F: 0,
      Other: 0,
      Total_Marks: 30,
      "A%": 60,
      "B%": 30,
      "C%": 10,
      "D%": 0,
      "F%": 0,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 95,
      TLN: "Rocco",
      TF: "Kendra",
      Teacher: "Kendra Rocco",
      Department: "English",
      Term: "PRG1",
      A: 24,
      B: 47,
      C: 9,
      D: 3,
      F: 30,
      Other: 0,
      Total_Marks: 113,
      "A%": 21.2,
      "B%": 41.6,
      "C%": 8,
      "D%": 2.7,
      "F%": 26.5,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 113,
      TLN: "Morris",
      TF: "Kellie",
      Teacher: "Kellie Morris",
      Department: "English",
      Term: "PRG3",
      A: 0,
      B: 0,
      C: 5,
      D: 9,
      F: 2,
      Other: 0,
      Total_Marks: 16,
      "A%": 0,
      "B%": 0,
      "C%": 31.3,
      "D%": 56.3,
      "F%": 12.5,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 818,
      TLN: "Stein",
      TF: "Sarah",
      Teacher: "Sarah Stein",
      Department: "English",
      Term: "PRG2",
      A: 27,
      B: 30,
      C: 25,
      D: 4,
      F: 8,
      Other: 0,
      Total_Marks: 94,
      "A%": 28.7,
      "B%": 31.9,
      "C%": 26.6,
      "D%": 4.3,
      "F%": 8.5,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 95,
      TLN: "Rocco",
      TF: "Kendra",
      Teacher: "Kendra Rocco",
      Department: "English",
      Term: "GRD1",
      A: 37,
      B: 39,
      C: 21,
      D: 9,
      F: 9,
      Other: 0,
      Total_Marks: 115,
      "A%": 32.2,
      "B%": 33.9,
      "C%": 18.3,
      "D%": 7.8,
      "F%": 7.8,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 70,
      TLN: "Chang",
      TF: "David",
      Teacher: "David Chang",
      Department: "English",
      Term: "PRG1",
      A: 92,
      B: 25,
      C: 9,
      D: 10,
      F: 11,
      Other: 0,
      Total_Marks: 147,
      "A%": 62.6,
      "B%": 17,
      "C%": 6.1,
      "D%": 6.8,
      "F%": 7.5,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 95,
      TLN: "Rocco",
      TF: "Kendra",
      Teacher: "Kendra Rocco",
      Department: "English",
      Term: "PRG2",
      A: 28,
      B: 33,
      C: 25,
      D: 21,
      F: 6,
      Other: 0,
      Total_Marks: 113,
      "A%": 24.8,
      "B%": 29.2,
      "C%": 22.1,
      "D%": 18.6,
      "F%": 5.3,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 85,
      TLN: "Sherman",
      TF: "Samantha",
      Teacher: "Samantha Sherman",
      Department: "English",
      Term: "GRD1",
      A: 48,
      B: 27,
      C: 28,
      D: 11,
      F: 6,
      Other: 0,
      Total_Marks: 120,
      "A%": 40,
      "B%": 22.5,
      "C%": 23.3,
      "D%": 9.2,
      "F%": 5,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 76,
      TLN: "Zehnder",
      TF: "Sara",
      Teacher: "Sara Zehnder",
      Department: "English",
      Term: "GRD2",
      A: 29,
      B: 45,
      C: 27,
      D: 11,
      F: 4,
      Other: 1,
      Total_Marks: 117,
      "A%": 24.8,
      "B%": 38.5,
      "C%": 23.1,
      "D%": 9.4,
      "F%": 3.4,
      Other_Percent: 0.9,
     },
   {
      SC: 12,
      TN: 76,
      TLN: "Zehnder",
      TF: "Sara",
      Teacher: "Sara Zehnder",
      Department: "English",
      Term: "PRG2",
      A: 71,
      B: 18,
      C: 20,
      D: 4,
      F: 4,
      Other: 0,
      Total_Marks: 117,
      "A%": 60.7,
      "B%": 15.4,
      "C%": 17.1,
      "D%": 3.4,
      "F%": 3.4,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 818,
      TLN: "Stein",
      TF: "Sarah",
      Teacher: "Sarah Stein",
      Department: "English",
      Term: "PRG3",
      A: 24,
      B: 32,
      C: 21,
      D: 15,
      F: 3,
      Other: 0,
      Total_Marks: 95,
      "A%": 25.3,
      "B%": 33.7,
      "C%": 22.1,
      "D%": 15.8,
      "F%": 3.2,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 818,
      TLN: "Stein",
      TF: "Sarah",
      Teacher: "Sarah Stein",
      Department: "English",
      Term: "GRD1",
      A: 37,
      B: 25,
      C: 21,
      D: 7,
      F: 3,
      Other: 0,
      Total_Marks: 93,
      "A%": 39.8,
      "B%": 26.9,
      "C%": 22.6,
      "D%": 7.5,
      "F%": 3.2,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 13,
      TLN: "Guerrero",
      TF: "Erika",
      Teacher: "Erika Guerrero",
      Department: "English",
      Term: "PRG1",
      A: 12,
      B: 20,
      C: 3,
      D: 0,
      F: 1,
      Other: 0,
      Total_Marks: 36,
      "A%": 33.3,
      "B%": 55.6,
      "C%": 8.3,
      "D%": 0,
      "F%": 2.8,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 43,
      TLN: "Griffith",
      TF: "Zachary",
      Teacher: "Zachary Griffith",
      Department: "English",
      Term: "PRG1",
      A: 52,
      B: 33,
      C: 13,
      D: 14,
      F: 3,
      Other: 0,
      Total_Marks: 115,
      "A%": 45.2,
      "B%": 28.7,
      "C%": 11.3,
      "D%": 12.2,
      "F%": 2.6,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 95,
      TLN: "Rocco",
      TF: "Kendra",
      Teacher: "Kendra Rocco",
      Department: "English",
      Term: "GRD2",
      A: 44,
      B: 30,
      C: 28,
      D: 9,
      F: 3,
      Other: 0,
      Total_Marks: 114,
      "A%": 38.6,
      "B%": 26.3,
      "C%": 24.6,
      "D%": 7.9,
      "F%": 2.6,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 13,
      TLN: "Guerrero",
      TF: "Erika",
      Teacher: "Erika Guerrero",
      Department: "English",
      Term: "GRD2",
      A: 4,
      B: 20,
      C: 14,
      D: 0,
      F: 1,
      Other: 0,
      Total_Marks: 39,
      "A%": 10.3,
      "B%": 51.3,
      "C%": 35.9,
      "D%": 0,
      "F%": 2.6,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 818,
      TLN: "Stein",
      TF: "Sarah",
      Teacher: "Sarah Stein",
      Department: "English",
      Term: "GRD2",
      A: 29,
      B: 28,
      C: 26,
      D: 9,
      F: 2,
      Other: 0,
      Total_Marks: 94,
      "A%": 30.9,
      "B%": 29.8,
      "C%": 27.7,
      "D%": 9.6,
      "F%": 2.1,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 113,
      TLN: "Morris",
      TF: "Kellie",
      Teacher: "Kellie Morris",
      Department: "English",
      Term: "PRG1",
      A: 47,
      B: 51,
      C: 9,
      D: 7,
      F: 2,
      Other: 0,
      Total_Marks: 116,
      "A%": 40.5,
      "B%": 44,
      "C%": 7.8,
      "D%": 6,
      "F%": 1.7,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 818,
      TLN: "Stein",
      TF: "Sarah",
      Teacher: "Sarah Stein",
      Department: "English",
      Term: "PRG1",
      A: 29,
      B: 35,
      C: 23,
      D: 6,
      F: 1,
      Other: 0,
      Total_Marks: 94,
      "A%": 30.9,
      "B%": 37.2,
      "C%": 24.5,
      "D%": 6.4,
      "F%": 1.1,
      Other_Percent: 0,
     },
   {
      SC: 12,
      TN: 113,
      TLN: "Morris",
      TF: "Kellie",
      Teacher: "Kellie Morris",
      Department: "English",
      Term: "GRD1",
      A: 30,
      B: 53,
      C: 24,
      D: 8,
      F: 1,
      Other: 0,
      Total_Marks: 116,
      "A%": 25.9,
      "B%": 45.7,
      "C%": 20.7,
      "D%": 6.9,
      "F%": 0.9,
      Other_Percent: 0,
    },
  ];